### ISSUE TITLE
TV instead of a Switch

### ISSUE THREAD

**Issue by xrust83** [marcelkordek/homebridge-tesvor#1]
Hello. I am very glad to hear about your plugin and have already installed it. Now it works like a switch, but I usually put a fan on. In the plugin configuration, I note that you can select different cleaning modes, which is great, but you can only choose one. What do you think if you make the device of the vacuum cleaner not a switch, but a Television. Cleaning modes could then be selected as input sources. A remote control would also be added and perhaps it would be possible to control the vacuum cleaner as well as a native remote control. These are of course fantasies and ideas. Your plugin is already very cool as you can control the vacuum cleaner through Siri and automation

And one more thing with the setting. Phone number in my country Ukraine +380501234567
But for your plugin to work, you need to enter the phone number 050123456789 and the country +380. The result is +3800505353663. Incorrectly entered data does not skip the plugin, but leads to a reboot of the permanent Homebridge.

**Comment by xrust83** [comment]
I tried to depict what I suggested above.  I think that would be great. 
![image](https://user-images.githubusercontent.com/58448955/111184570-c1b15380-85b9-11eb-95e8-b4df17ccb22c.png)
![image](https://user-images.githubusercontent.com/58448955/111184417-9fb7d100-85b9-11eb-97a2-aa8df890db8d.png)
Thanks for the battery level in version 1.0.6 👍

**Comment by xrust83** [comment]
I tried to substitute all the commands that can be selected in the on and off plugin on my Neatsvor X500 and got the following result.

AutoClean = Smart Cleaning - working
SmartClean - not working x500
EdgeClean = Border Cleaning - working
SpotClean = Pic Point Cleaning - working
RoomClean - not working x500

Standby - working
BockCharging - working

**Comment by marcelkordek** [comment]
Hi, good idea. I will include it as a selection. You can then choose between switch and tv. However, if tv is selected it must be added as a separate external device.

I look at the error with the login. Thank you for testing the different modes. I think that the modes are model-dependent.

**Comment by xrust83** [comment]
I saw that you added a TV category. But I could not get the selection of items as expected in the screenshot. Perhaps you need to do something like yours in another plugin? "inputs": ["STB","Cable Sat","Game"],

**Comment by marcelkordek** [comment]
Hi,

unfortunately it is not working as it should at the moment.
