### ISSUE TITLE
Need your help for connecting to WeBack server

### ISSUE THREAD

**Issue by Jezza34000** [marcelkordek/homebridge-tesvor#10]
Hi Marcel!
I send you this support request for a special request...
I actually made a plugin for HomeAssistant, and i have problem... i'm pretty sure you have the solution !

User's coming from Tesvor app can't connect with my plugin, cause server said the application is not recognized.
When you are login to WeBack server what do you insert inside "application" field ?

```
{
    "payload": {
        "opt": "login",
        "pwd": "xxxxxxxxxxxxxxxxxxxxxxx"
        },
    "header": {
        "language": "fr",
        "app_name": "", <==== HERE ?
        "calling_code": "0033",
        "api_version": "1.0",
        "account": "mymail@gmail.com",
        "client_id": "yugong_app"
    }
}
```

**Comment by waywit** [comment]
Just installing and trying around with this plugin... Perhaps this post helps you?

[Curl call and password has generation to test](https://github.com/marcelkordek/homebridge-tesvor/issues/4#issuecomment-1008611940)

**Comment by Jezza34000** [comment]
Hi !
No this post doesn't help me in this example app_name used is WeBack but doesn't work for Tesvor...
And i don't have homebridge

**Comment by marcelkordek** [comment]
Hi, 
I would like to help you, but unfortunately the Tesvor APP uses a different API.
My devices only work with the WeBack APP, so I can't test the Tesvor APP.
Maybe you can record the network traffic of the Tesvor APP. For example, a useful tool for iOS is HTTP Catcher.

Regards
Marcel
