### ISSUE TITLE
Update Möglich?

### ISSUE THREAD

**Issue by sangandi** [marcelkordek/homebridge-tesvor#4]
Servus!

Aktuell funktioniert das Plugin nicht. Ich denke da hat's sich was an der api geändert? Gibt es Hoffnung auf ein Update?

Wäre super. Habe 2 Tesvor Roboter und würde diese gern in HomeKit einfügen.

Gruß 
Sangandi

**Comment by marcelkordek** [comment]
Hallo Sangandi,
ich schaue mir den Fehler an. Bis jetzt konnte ich es bei nicht nachstellen. Alle drei Roboter funktionieren und lassen sich steuern. Kannst du Homebridge mal im DEBUG Modus laufen lassen und schauen was die Logs sagen?

Vielen Dank.

Gruß
Marcel

**Comment by sangandi** [comment]
Vielen Dank für die schnelle Antwort.
Ich werde heute Abend mal den log schicken. 

Gruß 
Sangandi

**Comment by sangandi** [comment]
Hallo, im log steht nur das:

Could not authenticate
[12/2/2021, 9:42:01 AM] TypeError: Cannot read properties of undefined (reading 'invoke')
    at /usr/lib/node_modules/homebridge-tesvor/src/lib/weback.js:136:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[12/2/2021, 9:42:01 AM] Got SIGTERM, shutting down Homebridge...
Could not authenticate

Homebridge version ist: v1.3.8
Node.js Version: v16.13.0
Npm Version: v8.1.4

Gruß
Sangandi

**Comment by marcelkordek** [comment]
Hallo, es gibt ein neues Update.
Bitte schaue nochmal noch den Logs.

Gruß
Marcel

**Comment by sangandi** [comment]
Hallo,

Jetzt Startet die Homebridge zwar nicht mehr neu, aber jetzt kommt:

[37m[12/3/2021, 5:02:18 PM] [39m[36m[HomebridgeTesvor][39m Could not authenticate:  {

  Request_Result: 'fail',

  Fail_Reason: 'account or password is incorrect'

}

[37m[12/3/2021, 5:02:18 PM] [39m[36m[HomebridgeTesvor][39m Could not authenticate:  {

  Request_Result: 'fail',

  Fail_Reason: 'account or password is incorrect'

}

Ich hab's mit der Emailadresse und Handynummer probiert.

Wenn ich daheim bin erstell ich mal nen neuen Account, vielleicht gehts ja dann.

Gruß 
Sangandi

**Comment by JoergW708** [comment]
Hallo, ich bekomme auch den Authentifizierungsfehler in der aktuellen Version:

24.12.2021, 00:27:54 [HomebridgeTesvor] Could not authenticate:  {
  Request_Result: 'fail',
  Fail_Reason: 'account or password is incorrect'
}

Das CURL-Kommando aus einem anderen Thread auch probiert - ebenfalls keine Authentifizierung möglich.

In der Tesvor-App ist der Saugroboter ganz normal eingerichtet (als einziges Gerät) und läuft. Passwort zwischenzeitlich auch auf ein schlichtes (10-stellig, nur Buchstaben/Zahlen) geändert - keine Besserung.

Liegt es eventuell an der neuen App? Muss in der alten WeBack-App das auch eingerichtet sein?

Gruss
Joerg

**Comment by github-kitsch** [comment]
hallo,

ich bekomme bei meinem neu erstellten account via weback leider auch die gleiche fehlermeldung wie Joerg. 

bei meinem alten account hat es kurz funktioniert, dann habe ich den tesvor allerdings neu einrichten müssen. 

seitdem ist der login möglich, aber das gerät wird nicht wie zuvor gefunden.

an sich eine mega gute idee und hat auch echt toll funktioniert. nur leider aktuell nicht mehr.

würde mich sehr freuen wenn das plugin weiter aktualisiert wird.

danke und gruß

**Comment by ErRoRDoX404** [comment]
Selber Fehler mit dem Login kommt bei mir auch. Gibt es noch Hoffnung auf ein Update?

**Comment by marcelkordek** [comment]
Hello, apparently the API of the WeBack app has changed. Please try to log in with:

```
curl --location --request POST 'https://user.grit-cloud.com/oauth' \
--header 'Content-Type: application/json' \
--data-raw '{
    "payload":{
        "opt":"login",
        "pwd": "HASHED PASSWORD"
    },
    "header":{
        "language":"de",
        "app_name":"WeBack",
        "calling_code":"COUNTRY CODE (0049)",
        "api_version":"1.0",
        "account":"EMAIL OR TEL",
        "client_id":"yugong_app"
    }
}'
```
To generate the HASH you can use:
```
echo -n PASSWORD | openssl md5
```

**Comment by github-kitsch** [comment]
blöde frage, aber wo muss dieser code eingegeben werden? danke und gruß

**Comment by marcelkordek** [comment]
Der Code im Terminal eingegeben werden

**Comment by github-kitsch** [comment]
Hallo marcel, bin deiner anleitung gefolgt, bekomme aber das plugin leider nicht mehr zum laufen.
Dennoch vielen dank für deine rückmeldung!

**Comment by Jezza34000** [comment]
> Hello, apparently the API of the WeBack app has changed. Please try to log in with:
> 
> ```
> curl --location --request POST 'https://user.grit-cloud.com/oauth' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "payload":{
>         "opt":"login",
>         "pwd": "HASHED PASSWORD"
>     },
>     "header":{
>         "language":"de",
>         "app_name":"WeBack",
>         "calling_code":"COUNTRY CODE (0049)",
>         "api_version":"1.0",
>         "account":"EMAIL OR TEL",
>         "client_id":"yugong_app"
>     }
> }'
> ```
> 
> To generate the HASH you can use:
> 
> ```
> echo -n PASSWORD | openssl md5
> ```

And after when you got the jwtToken ?

**Comment by FulytheFox** [comment]
Hey!
I think I found the solution. @marcelkordek already rewritten the API connection in the beta release of this repo. Just update to it and change the format of the country code (e.g. from `+49` to `0049`) in your configuration.

I hope a stable release will come soon too!
