### ISSUE TITLE
Restart loop

### ISSUE THREAD

**Issue by emilf44** [marcelkordek/homebridge-tesvor#5]
Hello I just installed the plugin and input my info and this error just loops:

Could not authenticate
TypeError: Cannot read properties of undefined (reading 'invoke')
    at /usr/lib/node_modules/homebridge-tesvor/src/lib/weback.js:136:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[30/11/2021, 21:55:43] [homebridge-tesvor] Child bridge process ended

**Comment by marcelkordek** [comment]
Hi, how did you configure the plugin?

greetings,
Marcel

**Comment by emilf44** [comment]
"username": "emilf44@xxxxxxxx",
            "password": "xxxxxxxx",
            "country": "00354",
            "accessoryType": "switch",
            "accessoryCategory": "TELEVISION",
            "startMode": "AutoClean",
            "stopMode": "BackCharging",
            "_bridge": {
                "username": "0E:BC:8B:09:C6:CC",
                "port": 49331
            },
            "platform": "HomebridgeTesvor"

**Comment by marcelkordek** [comment]
Hi,
please try '+354' instead of '00354'. This should work.

greetings

**Comment by xrust83** [comment]
I think it needs to be removed "accessoryCategory": "TELEVISION",
The "accessoryType": "switch", parameter does not imply the TV service 

I did not manage to register via mail in the beginning, I made an account by phone number and everything works fine

**Comment by marcelkordek** [comment]
@xrust83 yes, this is also wrong and could be removed

**Comment by emilf44** [comment]
I had already tried removing the accessoryCategory, something that came in automatically and tried both +354 and 00354 as the country code and still I get this:

Launched child bridge with PID 65034
[02/12/2021, 09:40:17] Registering platform 'homebridge-tesvor.HomebridgeTesvor'
[02/12/2021, 09:40:17] [homebridge-tesvor] Loaded homebridge-tesvor v1.0.7 child bridge successfully
[02/12/2021, 09:40:17] Loaded 0 cached accessories from cachedAccessories.0EBC8B09C6CC.
[02/12/2021, 09:40:17] Homebridge v1.3.8 (HAP v0.9.7) (homebridge-tesvor) is running on port 49331.
Could not authenticate
Could not authenticate
TypeError: Cannot read properties of undefined (reading 'invoke')
    at /usr/lib/node_modules/homebridge-tesvor/src/lib/weback.js:136:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by xrust83** [comment]
I'm not sure with the children's bridge, maybe the Mac address is sensitive to the register of letters

**Comment by xrust83** [comment]
What is your country and phone number? I am from Ukraine, my phone number is + 38050xxxxxxх
It is logical that at geestration it is necessary to specify

```
{
            "username": "50xxxxxxx",
            "password": "XXXXXX83",
            "country": "+380",
            "accessoryType": "Switch",
            "startMode": "AutoClean",
            "stopMode": "BackCharging",
            "platform": "HomebridgeTesvor"
        },

```

but it doesn't work that way

```
{
            "username": "050xxxxxxx",
            "password": "XXXXXX83",
            "country": "+380",
            "accessoryType": "Switch",
            "startMode": "AutoClean",
            "stopMode": "BackCharging",
            "platform": "HomebridgeTesvor"
        },
```

for the system my number looks like + 380050xxxxxxх
Vozhozhno and you have the same problem

**Comment by emilf44** [comment]
But I don't have my phone number setup as I just use an account name which is my email address. But maybe I have to use a phone number for the username.

**Comment by emilf44** [comment]
I think I solved the restart loop as I removed the country code option from my config and it looks like it starts only complaining that the country code is missing. I guess this is because the plugin always adds the country code to the username but as I am using an email address and not a phone number it couldn't connect earlier. 

But I am not at home and I haven't been able to connect to it through Homekit to test it further, although I should be able to because I can control everything even though I am not at home.

**Comment by emilf44** [comment]
I was able to add the bridge to my Homekit when I got home but no accessory shows up in the Homekit or the homebridge interface.

**Comment by marcelkordek** [comment]
Hi,

the country code is required for login.
There is a new update 1.0.8.

Please check the logs again.

Regards
Marcel

**Comment by emilf44** [comment]
It stays up now, after the update to 1.0.8, but gives me authentication failure account name or password wrong. I know both of those are correct, the country code is +354 for Iceland and it wont log me in..

**Comment by marcelkordek** [comment]
Did you create the account with the Tesvor or the Weback app?

**Comment by emilf44** [comment]
I have an account with both apps.. but I can only connect my robot to the Weback app.

**Comment by marcelkordek** [comment]
That's strange. Attached my config, I can login without a problem:

```
{
"username": "xxx@me.com",
"password": "XXX",
"country": "+49",
"accessoryType": "Switch",
"startMode": "AutoClean",
"stopMode": "BackCharging",
"platform": "HomebridgeTesvor"
}
```
I'm trying to make you a little script to test the login

**Comment by emilf44** [comment]
Yeah mine looks exactly the same..

**Comment by marcelkordek** [comment]
You can test the Login with curl:

```
curl --location --request POST 'https://www.weback-login.com/WeBack/WeBack_Login_Ats_V3' \
--header 'Content-Type: application/json' \
--data-raw '{
"App_Version": "android_3.9.3",
"Password": "HASHED PASSWORD",
"User_Account": "+354-EMAIL OR TEL"
}'
```

To generate the HASH you can use:
```
echo -n PASSWORD | openssl md5
```

**Comment by emilf44** [comment]
Still telling me that username or password is incorrect...

**Comment by emilf44** [comment]
I just reset my password and it didn't change anything.

**Comment by sangandi** [comment]
It's the same with me too. The tesvor app cannot find the vacuum cleaner.

**Comment by marcelkordek** [comment]
Maybe the password is too complex or has special characters. You can test it with a simple password.

Apparently not all vacuum robots are compatible with the tesvor app:
https://www.tesvor.com/de/user-mannul-app

**Comment by emilf44** [comment]
That is not it have both tried changing the password and using the wives account and always get the authentication failure

**Comment by sysonebr** [comment]
Same authentication failure for me too, even if I try test it on curl

**Comment by marcelkordek** [comment]
Which country was specified when registering? Maybe that doesn't match. Which country is shown in the weback app?

**Comment by sysonebr** [comment]
Brazil... but already try with +55 or +0055.... I have both accounts with email and via phone number, both connect on app, but via api fail

**Comment by marcelkordek** [comment]
Hello, apparently the API of the WeBack app has changed. Please try to log in with:

```
curl --location --request POST 'https://user.grit-cloud.com/oauth' \
--header 'Content-Type: application/json' \
--data-raw '{
    "payload":{
        "opt":"login",
        "pwd": "HASHED PASSWORD"
    },
    "header":{
        "language":"de",
        "app_name":"WeBack",
        "calling_code":"COUNTRY CODE (0049)",
        "api_version":"1.0",
        "account":"EMAIL OR TEL",
        "client_id":"yugong_app"
    }
}'
```
To generate the HASH you can use:
```
echo -n PASSWORD | openssl md5
```

**Comment by sysonebr** [comment]
Now the authentication works, but the api response seems totally different... I believe you already see that!   Anyway, to help, in attach the changes I made in authentication, and the new problem on aws server

![image](https://user-images.githubusercontent.com/32374849/148803320-4ad688b0-3c7a-4fd1-b513-611f466990df.png)

![image](https://user-images.githubusercontent.com/32374849/148803260-8c5690b9-770d-4757-bd24-7ca7080db11c.png)

**Comment by marcelkordek** [comment]
Ok perfect. Yes AWS doesn't work with it. 
The plugin has to be adapted for this. I hope that I can fix the problem in the next few days.

Regards
