### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by andrewfang** [marcelkordek/homebridge-tesvor#8]
I went through the instructions to add homebridge-tesvor, and I see the config that looks like your
```
{
           "username": "myemail@email.com", # E-Mail or Phone (Phone without Country-Code) e.g 123456 not +49123456
           "password": "PASS", # "Account Password."
           "country": "+1", # Country-Code
           "startMode": "AutoClean",
           "stopMode": "BackCharging",
           "platform": "HomebridgeTesvor"
}
```

Looking at the logs, it says my authentication failed, but I am able to log in just fine in the WeBack app using my email and password. Does your Auth API use a different set of Auth params? I’m in the USA.

**Comment by john-pierre** [comment]
I have the same problem. WeBack App is working fine with my credentials.

**Comment by feduza** [comment]
Try my [fork](https://github.com/marcelkordek/homebridge-tesvor/pull/9)

**Comment by AviatorBimmer** [comment]
Nevermind, I fixed it. For USA users, you need to enter 001 for Country Code, NOT +1.

**Comment by AviatorBimmer** [comment]
> I went through the instructions to add homebridge-tesvor, and I see the config that looks like your
> 
> ```
> {
>            "username": "myemail@email.com", # E-Mail or Phone (Phone without Country-Code) e.g 123456 not +49123456
>            "password": "PASS", # "Account Password."
>            "country": "+1", # Country-Code
>            "startMode": "AutoClean",
>            "stopMode": "BackCharging",
>            "platform": "HomebridgeTesvor"
> }
> ```
> 
> Looking at the logs, it says my authentication failed, but I am able to log in just fine in the WeBack app using my email and password. Does your Auth API use a different set of Auth params? I’m in the USA.

Enter 001 for Country Code. NOT +1.
